#! /bin/bash

if [[ "$#" -eq "0" ]]; then
  echo "I need at least a file to feed pandoc."
fi

FILE=${1%.md}
shift

pandoc -t html5 -s -S -c assets/style.css -H assets/header.html -B assets/b4body.html -A assets/footer.html "$FILE.md" -o "$FILE.html"
