#! /bin/bash

if [[ "$#" -eq "0" ]]; then
  echo "I need at least a file to feed pandoc."
  exit 1
fi

FILE=${1%.md}
shift

pandoc --template my-html5.template -f markdown+smart -t html5 -s -c assets/style.css -H assets/header.html -B assets/b4body.html -A assets/footer.html "$FILE.md" -o "$FILE.html"
